// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate
{
    public static class GetTwingateRemoteNetworks
    {
        public static Task<GetTwingateRemoteNetworksResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTwingateRemoteNetworksResult>("twingate:index/getTwingateRemoteNetworks:getTwingateRemoteNetworks", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetTwingateRemoteNetworksResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTwingateRemoteNetworksResult>("twingate:index/getTwingateRemoteNetworks:getTwingateRemoteNetworks", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetTwingateRemoteNetworksResult
    {
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetTwingateRemoteNetworksRemoteNetworkResult> RemoteNetworks;

        [OutputConstructor]
        private GetTwingateRemoteNetworksResult(
            string id,

            ImmutableArray<Outputs.GetTwingateRemoteNetworksRemoteNetworkResult> remoteNetworks)
        {
            Id = id;
            RemoteNetworks = remoteNetworks;
        }
    }
}
