// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate
{
    public static class GetTwingateUser
    {
        public static Task<GetTwingateUserResult> InvokeAsync(GetTwingateUserArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTwingateUserResult>("twingate:index/getTwingateUser:getTwingateUser", args ?? new GetTwingateUserArgs(), options.WithDefaults());

        public static Output<GetTwingateUserResult> Invoke(GetTwingateUserInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTwingateUserResult>("twingate:index/getTwingateUser:getTwingateUser", args ?? new GetTwingateUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTwingateUserArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetTwingateUserArgs()
        {
        }
        public static new GetTwingateUserArgs Empty => new GetTwingateUserArgs();
    }

    public sealed class GetTwingateUserInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetTwingateUserInvokeArgs()
        {
        }
        public static new GetTwingateUserInvokeArgs Empty => new GetTwingateUserInvokeArgs();
    }


    [OutputType]
    public sealed class GetTwingateUserResult
    {
        public readonly string Email;
        public readonly string FirstName;
        public readonly string Id;
        public readonly bool IsAdmin;
        public readonly string LastName;
        public readonly string Role;

        [OutputConstructor]
        private GetTwingateUserResult(
            string email,

            string firstName,

            string id,

            bool isAdmin,

            string lastName,

            string role)
        {
            Email = email;
            FirstName = firstName;
            Id = id;
            IsAdmin = isAdmin;
            LastName = lastName;
            Role = role;
        }
    }
}
