# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetTwingateConnectorsResult',
    'AwaitableGetTwingateConnectorsResult',
    'get_twingate_connectors',
    'get_twingate_connectors_output',
]

@pulumi.output_type
class GetTwingateConnectorsResult:
    """
    A collection of values returned by getTwingateConnectors.
    """
    def __init__(__self__, connectors=None, id=None):
        if connectors and not isinstance(connectors, list):
            raise TypeError("Expected argument 'connectors' to be a list")
        pulumi.set(__self__, "connectors", connectors)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def connectors(self) -> Optional[Sequence['outputs.GetTwingateConnectorsConnectorResult']]:
        return pulumi.get(self, "connectors")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetTwingateConnectorsResult(GetTwingateConnectorsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTwingateConnectorsResult(
            connectors=self.connectors,
            id=self.id)


def get_twingate_connectors(connectors: Optional[Sequence[pulumi.InputType['GetTwingateConnectorsConnectorArgs']]] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTwingateConnectorsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['connectors'] = connectors
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('twingate:index/getTwingateConnectors:getTwingateConnectors', __args__, opts=opts, typ=GetTwingateConnectorsResult).value

    return AwaitableGetTwingateConnectorsResult(
        connectors=__ret__.connectors,
        id=__ret__.id)


@_utilities.lift_output_func(get_twingate_connectors)
def get_twingate_connectors_output(connectors: Optional[pulumi.Input[Optional[Sequence[pulumi.InputType['GetTwingateConnectorsConnectorArgs']]]]] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetTwingateConnectorsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
