archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
builds:
- binary: pulumi-resource-twingate
  dir: provider
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ignore: []
  ldflags:
  - -X github.com/Twingate-Labs/pulumi-twingate/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-twingate/
changelog:
  sort: asc
  use: git
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
