// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate.Outputs
{

    [OutputType]
    public sealed class GetTwingateGroupsGroupResult
    {
        public readonly string Id;
        public readonly bool IsActive;
        public readonly string Name;
        public readonly string Type;

        [OutputConstructor]
        private GetTwingateGroupsGroupResult(
            string id,

            bool isActive,

            string name,

            string type)
        {
            Id = id;
            IsActive = isActive;
            Name = name;
            Type = type;
        }
    }
}
