// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate.Inputs
{

    public sealed class GetTwingateResourcesResourceProtocolUdpArgs : global::Pulumi.InvokeArgs
    {
        [Input("policy", required: true)]
        public string Policy { get; set; } = null!;

        [Input("ports", required: true)]
        private List<string>? _ports;
        public List<string> Ports
        {
            get => _ports ?? (_ports = new List<string>());
            set => _ports = value;
        }

        public GetTwingateResourcesResourceProtocolUdpArgs()
        {
        }
        public static new GetTwingateResourcesResourceProtocolUdpArgs Empty => new GetTwingateResourcesResourceProtocolUdpArgs();
    }
}
