package twingate

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/twingate/go-graphql-client"
)

func resourceGroup() *schema.Resource {
	return &schema.Resource{
		Description:   "Groups are how users are authorized to access Resources. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/groups).",
		CreateContext: resourceGroupCreate,
		ReadContext:   resourceGroupRead,
		DeleteContext: resourceGroupDelete,
		UpdateContext: resourceGroupUpdate,

		Schema: map[string]*schema.Schema{
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The name of the group",
			},
			"users": {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Optional:    true,
				Description: "List of user IDs",
			},
			"resources": {
				Type:        schema.TypeSet,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Optional:    true,
				Description: "List of resource IDs",
			},
			// computed
			"id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Autogenerated ID of the Resource, encoded in base64",
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceGroupCreate(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*Client)

	group, err := client.createGroup(ctx, extractGroupFromResourceData(resourceData))
	if err != nil {
		return diag.FromErr(err)
	}

	log.Printf("[INFO] Group %s created with id %v", group.Name, group.ID)

	return resourceGroupReadHelper(resourceData, group, nil)
}

func convertToStrings(input []interface{}) []string {
	if len(input) == 0 {
		return nil
	}

	str := make([]string, 0, len(input))

	for _, v := range input {
		s, ok := v.(string)
		if ok {
			str = append(str, s)
		}
	}

	return str
}

func resourceGroupUpdate(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*Client)

	group, err := client.updateGroup(ctx, extractGroupUpdateFromResourceData(resourceData))
	if err == nil {
		log.Printf("[INFO] Updated group id %v", group.ID)
	}

	return resourceGroupReadHelper(resourceData, group, err)
}

func extractGroupFromResourceData(resourceData *schema.ResourceData) *Group {
	return &Group{
		ID:        graphql.ID(resourceData.Id()),
		Name:      graphql.String(resourceData.Get("name").(string)),
		Users:     convertTerraformListToGraphqlIDs(resourceData.Get("users")),
		Resources: convertTerraformListToGraphqlIDs(resourceData.Get("resources")),
	}
}

func extractGroupUpdateFromResourceData(resourceData *schema.ResourceData) *GroupUpdateRequest {
	oldUsers, newUsers := resourceData.GetChange("users")
	oldResources, newResources := resourceData.GetChange("resources")

	return &GroupUpdateRequest{
		ID:           graphql.ID(resourceData.Id()),
		Name:         graphql.String(resourceData.Get("name").(string)),
		NewUsers:     convertTerraformListToGraphqlIDs(newUsers),
		OldUsers:     convertTerraformListToGraphqlIDs(oldUsers),
		NewResources: convertTerraformListToGraphqlIDs(newResources),
		OldResources: convertTerraformListToGraphqlIDs(oldResources),
	}
}

func convertTerraformListToGraphqlIDs(value interface{}) []graphql.ID {
	result := make([]graphql.ID, 0)

	if value == nil {
		return result
	}

	set, ok := value.(*schema.Set)
	if !ok || set == nil {
		return result
	}

	list := set.List()
	if len(list) == 0 {
		return result
	}

	return convertToGraphqlIDs(convertToStrings(list))
}

func resourceGroupDelete(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*Client)

	var diags diag.Diagnostics

	groupID := resourceData.Id()

	err := client.deleteGroup(ctx, groupID)
	if err != nil {
		return diag.FromErr(err)
	}

	log.Printf("[INFO] Deleted group id %s", resourceData.Id())

	return diags
}

func resourceGroupRead(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*Client)

	group, err := client.readGroup(ctx, resourceData.Id())

	return resourceGroupReadHelper(resourceData, group, err)
}

func resourceGroupReadHelper(resourceData *schema.ResourceData, group *Group, err error) diag.Diagnostics {
	if err != nil {
		if errors.Is(err, ErrGraphqlResultIsEmpty) {
			// clear state
			resourceData.SetId("")

			return nil
		}

		return diag.FromErr(err)
	}

	if err := resourceData.Set("name", group.Name); err != nil {
		return diag.FromErr(err)
	}

	if err := resourceData.Set("users", toStringIDs(group.Users)); err != nil {
		return diag.FromErr(err)
	}

	if err := resourceData.Set("resources", toStringIDs(group.Resources)); err != nil {
		return diag.FromErr(err)
	}

	resourceData.SetId(group.ID.(string))

	return nil
}

func toStringIDs(input []graphql.ID) []string {
	ids := make([]string, 0, len(input))

	for _, id := range input {
		ids = append(ids, fmt.Sprintf("%v", id))
	}

	return ids
}
