package attr

const (
	Priority                        = "priority"
	FallbackMethod                  = "fallback_method"
	AllowedDomains                  = "allowed_domains"
	DeniedDomains                   = "denied_domains"
	Domains                         = "domains"
	PrivacyCategories               = "privacy_categories"
	BlockAffiliateLinks             = "block_affiliate_links"
	BlockDisguisedTrackers          = "block_disguised_trackers"
	BlockAdsAndTrackers             = "block_ads_and_trackers"
	SecurityCategories              = "security_categories"
	EnableThreatIntelligenceFeeds   = "enable_threat_intelligence_feeds"
	EnableGoogleSafeBrowsing        = "enable_google_safe_browsing"
	BlockCryptojacking              = "block_cryptojacking"
	BlockIdnHomoglyph               = "block_idn_homoglyph"
	BlockTyposquatting              = "block_typosquatting"
	BlockDNSRebinding               = "block_dns_rebinding"
	BlockNewlyRegisteredDomains     = "block_newly_registered_domains"
	BlockDomainGenerationAlgorithms = "block_domain_generation_algorithms"
	BlockParkedDomains              = "block_parked_domains"
	ContentCategories               = "content_categories"
	BlockGambling                   = "block_gambling"
	BlockDating                     = "block_dating"
	BlockAdultContent               = "block_adult_content"
	BlockSocialMedia                = "block_social_media"
	BlockGames                      = "block_games"
	BlockStreaming                  = "block_streaming"
	BlockPiracy                     = "block_piracy"
	EnableYoutubeRestrictedMode     = "enable_youtube_restricted_mode"
	EnableSafesearch                = "enable_safesearch"
)
