package attr

const (
	Access                         = "access"
	AccessGroup                    = "access_group"
	UsageBasedAutolockDurationDays = "usage_based_autolock_duration_days"
	AccessService                  = "access_service"
	GroupIDs                       = "group_ids"
	GroupID                        = "group_id"
	ServiceAccountIDs              = "service_account_ids"
	IsAuthoritative                = "is_authoritative"
	Policy                         = "policy"
	Ports                          = "ports"
	Address                        = "address"
	Protocols                      = "protocols"
	AllowIcmp                      = "allow_icmp"
	TCP                            = "tcp"
	UDP                            = "udp"
	IsVisible                      = "is_visible"
	IsBrowserShortcutEnabled       = "is_browser_shortcut_enabled"
	Resources                      = "resources"
	ApprovalMode                   = "approval_mode"
	Tags                           = "tags"
	TagsAll                        = "tags_all"
	AccessPolicy                   = "access_policy"
	Mode                           = "mode"
	Duration                       = "duration"
)
