// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getTwingateResources(args: GetTwingateResourcesArgs, opts?: pulumi.InvokeOptions): Promise<GetTwingateResourcesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("twingate:index/getTwingateResources:getTwingateResources", {
        "name": args.name,
        "resources": args.resources,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateResources.
 */
export interface GetTwingateResourcesArgs {
    name: string;
    resources?: inputs.GetTwingateResourcesResource[];
}

/**
 * A collection of values returned by getTwingateResources.
 */
export interface GetTwingateResourcesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly resources?: outputs.GetTwingateResourcesResource[];
}
export function getTwingateResourcesOutput(args: GetTwingateResourcesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTwingateResourcesResult> {
    return pulumi.output(args).apply((a: any) => getTwingateResources(a, opts))
}

/**
 * A collection of arguments for invoking getTwingateResources.
 */
export interface GetTwingateResourcesOutputArgs {
    name: pulumi.Input<string>;
    resources?: pulumi.Input<pulumi.Input<inputs.GetTwingateResourcesResourceArgs>[]>;
}
