// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTwingateSecurityPolicy(args?: GetTwingateSecurityPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetTwingateSecurityPolicyResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("twingate:index/getTwingateSecurityPolicy:getTwingateSecurityPolicy", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateSecurityPolicy.
 */
export interface GetTwingateSecurityPolicyArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getTwingateSecurityPolicy.
 */
export interface GetTwingateSecurityPolicyResult {
    readonly id?: string;
    readonly name?: string;
}
export function getTwingateSecurityPolicyOutput(args?: GetTwingateSecurityPolicyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTwingateSecurityPolicyResult> {
    return pulumi.output(args).apply((a: any) => getTwingateSecurityPolicy(a, opts))
}

/**
 * A collection of arguments for invoking getTwingateSecurityPolicy.
 */
export interface GetTwingateSecurityPolicyOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
