// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getTwingateServiceAccounts(args?: GetTwingateServiceAccountsArgs, opts?: pulumi.InvokeOptions): Promise<GetTwingateServiceAccountsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("twingate:index/getTwingateServiceAccounts:getTwingateServiceAccounts", {
        "name": args.name,
        "serviceAccounts": args.serviceAccounts,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateServiceAccounts.
 */
export interface GetTwingateServiceAccountsArgs {
    name?: string;
    serviceAccounts?: inputs.GetTwingateServiceAccountsServiceAccount[];
}

/**
 * A collection of values returned by getTwingateServiceAccounts.
 */
export interface GetTwingateServiceAccountsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name?: string;
    readonly serviceAccounts?: outputs.GetTwingateServiceAccountsServiceAccount[];
}
export function getTwingateServiceAccountsOutput(args?: GetTwingateServiceAccountsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTwingateServiceAccountsResult> {
    return pulumi.output(args).apply((a: any) => getTwingateServiceAccounts(a, opts))
}

/**
 * A collection of arguments for invoking getTwingateServiceAccounts.
 */
export interface GetTwingateServiceAccountsOutputArgs {
    name?: pulumi.Input<string>;
    serviceAccounts?: pulumi.Input<pulumi.Input<inputs.GetTwingateServiceAccountsServiceAccountArgs>[]>;
}
