// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTwingateConnector(args: GetTwingateConnectorArgs, opts?: pulumi.InvokeOptions): Promise<GetTwingateConnectorResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("twingate:index/getTwingateConnector:getTwingateConnector", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getTwingateConnector.
 */
export interface GetTwingateConnectorArgs {
    id: string;
}

/**
 * A collection of values returned by getTwingateConnector.
 */
export interface GetTwingateConnectorResult {
    readonly id: string;
    readonly name: string;
    readonly remoteNetworkId: string;
    readonly statusUpdatesEnabled: boolean;
}
export function getTwingateConnectorOutput(args: GetTwingateConnectorOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTwingateConnectorResult> {
    return pulumi.output(args).apply((a: any) => getTwingateConnector(a, opts))
}

/**
 * A collection of arguments for invoking getTwingateConnector.
 */
export interface GetTwingateConnectorOutputArgs {
    id: pulumi.Input<string>;
}
