// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TwingateLabs.Twingate.Outputs
{

    [OutputType]
    public sealed class GetTwingateServiceAccountsServiceAccountResult
    {
        public readonly string Id;
        public readonly ImmutableArray<string> KeyIds;
        public readonly string Name;
        public readonly ImmutableArray<string> ResourceIds;

        [OutputConstructor]
        private GetTwingateServiceAccountsServiceAccountResult(
            string id,

            ImmutableArray<string> keyIds,

            string name,

            ImmutableArray<string> resourceIds)
        {
            Id = id;
            KeyIds = keyIds;
            Name = name;
            ResourceIds = resourceIds;
        }
    }
}
