package resource

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/Twingate/terraform-provider-twingate/twingate/internal/transport"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

var ErrNotAllowChangeRemoteNetworkID = errors.New("connectors cannot be moved between Remote Networks: you must either create a new Connector or destroy and recreate the existing one")

func Connector() *schema.Resource {
	return &schema.Resource{
		Description:   "Connectors provide connectivity to Remote Networks. This resource type will create the Connector in the Twingate Admin Console, but in order to successfully deploy it, you must also generate Connector tokens that authenticate the Connector with Twingate. For more information, see Twingate's [documentation](https://docs.twingate.com/docs/understanding-access-nodes).",
		CreateContext: connectorCreate,
		ReadContext:   connectorRead,
		DeleteContext: connectorDelete,
		UpdateContext: connectorUpdate,
		CustomizeDiff: func(ctx context.Context, d *schema.ResourceDiff, m interface{}) error {
			const key = "remote_network_id"
			oldVal, _ := d.GetChange(key)
			old := oldVal.(string)
			if old != "" && d.HasChange(key) {
				return ErrNotAllowChangeRemoteNetworkID
			}

			return nil
		},

		Schema: map[string]*schema.Schema{
			// required
			"remote_network_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The ID of the Remote Network the Connector is attached to",
			},
			"name": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Name of the Connector, if not provided one will be generated",
			},
			// computed
			"id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Autogenerated ID of the Connector, encoded in base64",
			},
		},
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func connectorCreate(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*transport.Client)

	remoteNetworkID := resourceData.Get("remote_network_id").(string)
	connector, err := client.CreateConnector(ctx, remoteNetworkID)

	if err != nil {
		return diag.FromErr(err)
	}

	resourceData.SetId(connector.ID)
	log.Printf("[INFO] Created conector %s", connector.Name)

	if resourceData.Get("name").(string) != "" {
		return connectorUpdate(ctx, resourceData, meta)
	}

	waitForResourceAvailability()

	return connectorRead(ctx, resourceData, meta)
}
func connectorUpdate(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*transport.Client)

	connectorName := resourceData.Get("name").(string)

	if resourceData.HasChange("name") {
		connectorID := resourceData.Id()
		log.Printf("[INFO] Updating name of connector id %s", connectorID)

		if err := client.UpdateConnector(ctx, connectorID, connectorName); err != nil {
			return diag.FromErr(err)
		}
	}

	return connectorRead(ctx, resourceData, meta)
}
func connectorDelete(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*transport.Client)

	var diags diag.Diagnostics

	connectorID := resourceData.Id()

	err := client.DeleteConnector(ctx, connectorID)
	if err != nil {
		return diag.FromErr(err)
	}

	log.Printf("[INFO] Destroyed connector id %s", connectorID)

	return diags
}

func connectorRead(ctx context.Context, resourceData *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*transport.Client)

	var diags diag.Diagnostics

	connectorID := resourceData.Id()
	connector, err := client.ReadConnector(ctx, connectorID)

	if err != nil {
		if errors.Is(err, transport.ErrGraphqlResultIsEmpty) {
			// clear state
			resourceData.SetId("")

			return nil
		}

		return diag.FromErr(err)
	}

	if err := resourceData.Set("name", connector.Name); err != nil {
		return diag.FromErr(fmt.Errorf("error setting name: %w ", err))
	}

	if err := resourceData.Set("remote_network_id", connector.NetworkID); err != nil {
		return diag.FromErr(fmt.Errorf("error setting remote_network_id: %w ", err))
	}

	return diags
}
