package resource

import (
	"context"
	"errors"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customvalidator"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/provider/providerdata"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure the implementation satisfies the desired interfaces.
var _ resource.Resource = &gateway{}

func NewGatewayResource() resource.Resource {
	return &gateway{}
}

type gateway struct {
	client *client.Client
}

type gatewayModel struct {
	ID              types.String `tfsdk:"id"`
	RemoteNetworkID types.String `tfsdk:"remote_network_id"`
	Address         types.String `tfsdk:"address"`
	X509CAID        types.String `tfsdk:"x509_ca_id"`
	SSHCAID         types.String `tfsdk:"ssh_ca_id"`
}

func (r *gateway) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateGateway
}

func (r *gateway) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		return
	}

	r.client = providerData.Client
}

func (r *gateway) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

func (r *gateway) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Gateways are the Twingate components that route traffic to remote networks.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the Gateway.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.RemoteNetworkID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Remote Network the Gateway belongs to.",
			},
			attr.Address: schema.StringAttribute{
				Required:    true,
				Description: "The address of the Gateway.",
				Validators: []validator.String{
					customvalidator.AddressWithPort(),
				},
			},
			attr.X509CAID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the X.509 Certificate Authority used for TLS.",
			},
			attr.SSHCAID: schema.StringAttribute{
				Optional:    true,
				Description: "The ID of the SSH Certificate Authority used for SSH access.",
			},
		},
	}
}

func (r *gateway) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan gatewayModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	gateway, err := r.client.CreateGateway(ctx,
		plan.Address.ValueString(),
		plan.RemoteNetworkID.ValueString(),
		plan.X509CAID.ValueString(),
		plan.SSHCAID.ValueString(),
	)

	r.helper(ctx, gateway, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *gateway) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state gatewayModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	gw, err := r.client.ReadGateway(ctx, state.ID.ValueString())

	r.helper(ctx, gw, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

func (r *gateway) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan gatewayModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	// Read remote_network_id from state (required by API, value never changes due to RequiresReplace).
	var state gatewayModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	gateway, err := r.client.UpdateGateway(ctx, &model.Gateway{
		ID:              state.ID.ValueString(),
		Address:         plan.Address.ValueString(),
		RemoteNetworkID: state.RemoteNetworkID.ValueString(),
		X509CAID:        plan.X509CAID.ValueString(),
		SSHCAID:         plan.SSHCAID.ValueString(),
	})

	r.helper(ctx, gateway, &plan, &resp.State, &resp.Diagnostics, err, operationUpdate)
}

func (r *gateway) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state gatewayModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteGateway(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateGateway)
}

func (r *gateway) helper(ctx context.Context, gateway *model.Gateway, state *gatewayModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateGateway)

		return
	}

	state.ID = types.StringValue(gateway.ID)
	state.Address = types.StringValue(gateway.Address)
	state.RemoteNetworkID = types.StringValue(gateway.RemoteNetworkID)
	state.X509CAID = types.StringValue(gateway.X509CAID)

	if gateway.SSHCAID != "" {
		state.SSHCAID = types.StringValue(gateway.SSHCAID)
	} else {
		state.SSHCAID = types.StringNull()
	}

	diags := respState.Set(ctx, state)
	diagnostics.Append(diags...)
}
