package resource //nolint:dupl

import (
	"context"
	"errors"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customvalidator"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &kubernetesResource{}

func NewKubernetesResourceResource() resource.Resource {
	return &kubernetesResource{}
}

type kubernetesResource struct {
	client *client.Client
}

type kubernetesResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Address         types.String `tfsdk:"address"`
	GatewayID       types.String `tfsdk:"gateway_id"`
	RemoteNetworkID types.String `tfsdk:"remote_network_id"`
	InCluster       types.Bool   `tfsdk:"in_cluster"`
}

func (r *kubernetesResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateKubernetesResource
}

func (r *kubernetesResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(*client.Client)
}

func (r *kubernetesResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

func (r *kubernetesResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Kubernetes Resources are Twingate resources accessed via a Kubernetes Gateway.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the Kubernetes Resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.Name: schema.StringAttribute{
				Required:    true,
				Description: "The name of the Kubernetes Resource.",
			},
			attr.Address: schema.StringAttribute{
				Required:    true,
				Description: "The address of the Kubernetes Resource (IP or FQDN).",
				Validators: []validator.String{
					customvalidator.Address(),
				},
			},
			attr.GatewayID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Gateway used to access this Kubernetes Resource.",
			},
			attr.RemoteNetworkID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Remote Network the Kubernetes Resource belongs to.",
			},
			attr.InCluster: schema.BoolAttribute{
				Optional:    true,
				Description: "Whether the Kubernetes Resource is running inside the cluster.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *kubernetesResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan kubernetesResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	k8sRes, err := r.client.CreateKubernetesResource(ctx, &model.KubernetesResource{
		Name:            plan.Name.ValueString(),
		Address:         plan.Address.ValueString(),
		GatewayID:       plan.GatewayID.ValueString(),
		RemoteNetworkID: plan.RemoteNetworkID.ValueString(),
	})

	r.helper(ctx, k8sRes, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *kubernetesResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state kubernetesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	k8sRes, err := r.client.ReadKubernetesResource(ctx, state.ID.ValueString())

	r.helper(ctx, k8sRes, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

func (r *kubernetesResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan kubernetesResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	var state kubernetesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	k8sRes, err := r.client.UpdateKubernetesResource(ctx, &model.KubernetesResource{
		ID:              state.ID.ValueString(),
		Name:            plan.Name.ValueString(),
		Address:         plan.Address.ValueString(),
		GatewayID:       plan.GatewayID.ValueString(),
		RemoteNetworkID: plan.RemoteNetworkID.ValueString(),
	})

	r.helper(ctx, k8sRes, &plan, &resp.State, &resp.Diagnostics, err, operationUpdate)
}

func (r *kubernetesResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state kubernetesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteKubernetesResource(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateKubernetesResource)
}

func (r *kubernetesResource) helper(ctx context.Context, k8sRes *model.KubernetesResource, state *kubernetesResourceModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateKubernetesResource)

		return
	}

	state.ID = types.StringValue(k8sRes.ID)
	state.Name = types.StringValue(k8sRes.Name)
	state.Address = types.StringValue(k8sRes.Address)
	state.GatewayID = types.StringValue(k8sRes.GatewayID)
	state.RemoteNetworkID = types.StringValue(k8sRes.RemoteNetworkID)

	diags := respState.Set(ctx, state)
	diagnostics.Append(diags...)
}
