package resource

import (
	"context"
	"errors"
	"fmt"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customvalidator"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/provider/providerdata"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

const defaultKubernetesAddress = "kubernetes.default.svc.cluster.local"

var (
	ErrBearerTokenFileEmpty = errors.New("bearer_token_file cannot be empty")
	ErrCAFileEmpty          = errors.New("ca_file cannot be empty")
	ErrAddressEmpty         = errors.New("address cannot be empty")
)

var _ resource.Resource = &kubernetesResource{}

func NewKubernetesResourceResource() resource.Resource {
	return &kubernetesResource{}
}

type kubernetesResource struct {
	client *client.Client
}

type kubernetesResourceModel struct {
	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	Address          types.String `tfsdk:"address"`
	BearerTokenFile  types.String `tfsdk:"bearer_token_file"`
	CAFile           types.String `tfsdk:"ca_file"`
	GatewayID        types.String `tfsdk:"gateway_id"`
	RemoteNetworkID  types.String `tfsdk:"remote_network_id"`
	InCluster        types.Bool   `tfsdk:"in_cluster"`
	IsVisible        types.Bool   `tfsdk:"is_visible"`
	Alias            types.String `tfsdk:"alias"`
	SecurityPolicyID types.String `tfsdk:"security_policy_id"`
	Tags             types.Map    `tfsdk:"tags"`
	Protocols        types.Object `tfsdk:"protocols"`
	AccessPolicy     types.Set    `tfsdk:"access_policy"`
	GroupAccess      types.Set    `tfsdk:"access_group"`
}

func (r *kubernetesResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateKubernetesResource
}

func (r *kubernetesResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		return
	}

	r.client = providerData.Client
}

func (r *kubernetesResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

//nolint:funlen
func (r *kubernetesResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Kubernetes Resources are Twingate resources accessed via a Gateway.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the Kubernetes Resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.Name: schema.StringAttribute{
				Required:    true,
				Description: "The name of the Kubernetes Resource.",
			},
			attr.Address: schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "The address of the Kubernetes Resource (IP or FQDN).",
				Validators: []validator.String{
					customvalidator.Address(),
				},
			},
			attr.GatewayID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Gateway used to access this Kubernetes Resource.",
			},
			attr.RemoteNetworkID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Remote Network the Kubernetes Resource belongs to.",
			},
			attr.InCluster: schema.BoolAttribute{
				Optional:    true,
				Description: "Whether the Gateway is running inside the same Kubernetes cluster that is represented by the Kubernetes Resource.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			attr.BearerTokenFile: schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "Path to bearer token file.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			attr.CAFile: schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "Path to CA certificate file.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			attr.IsVisible: schema.BoolAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.",
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			attr.Alias: schema.StringAttribute{
				Optional:      true,
				Description:   "Set a DNS alias address for the Resource. Must be a DNS-valid name string.",
				PlanModifiers: []planmodifier.String{CaseInsensitiveDiff()},
			},
			attr.SecurityPolicyID: schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "The ID of a `twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.",
				PlanModifiers: []planmodifier.String{
					UseNullPolicyForGroupAccessWhenValueOmitted(),
				},
			},
			attr.Tags: schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "A map of key-value pair tags to set on this resource.",
				Default:     mapdefault.StaticValue(types.MapNull(types.StringType)),
			},
			attr.Protocols: protocols(),
		},
		Blocks: map[string]schema.Block{
			attr.AccessPolicy: accessPolicyBlock(),
			attr.AccessGroup:  groupAccessBlock(),
		},
	}
}

//nolint:funlen
func (r *kubernetesResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan kubernetesResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	if !plan.InCluster.ValueBool() {
		if plan.BearerTokenFile.ValueString() == "" {
			addErr(&resp.Diagnostics, ErrBearerTokenFileEmpty, operationCreate, TwingateKubernetesResource)

			return
		}

		if plan.CAFile.ValueString() == "" {
			addErr(&resp.Diagnostics, ErrCAFileEmpty, operationCreate, TwingateKubernetesResource)

			return
		}
	}

	accessGroups, err := getGroupAccessAttribute(plan.GroupAccess)
	if err != nil {
		addErr(&resp.Diagnostics, fmt.Errorf("failed to parse access_group: %w", err), operationCreate, TwingateKubernetesResource)

		return
	}

	protocols, err := convertProtocols(&plan.Protocols)
	if err != nil {
		addErr(&resp.Diagnostics, err, operationCreate, TwingateKubernetesResource)

		return
	}

	accessPolicy, err := getAccessPolicyAttribute(plan.AccessPolicy)
	if err != nil {
		addErr(&resp.Diagnostics, fmt.Errorf("failed to parse access_policy: %w", err), operationCreate, TwingateKubernetesResource)

		return
	}

	address := plan.Address.ValueString()
	if plan.InCluster.ValueBool() {
		address = defaultKubernetesAddress
	}

	if address == "" {
		addErr(&resp.Diagnostics, ErrAddressEmpty, operationCreate, TwingateKubernetesResource)

		return
	}

	k8sRes, err := r.client.CreateKubernetesResource(ctx, &model.KubernetesResource{
		Name:             plan.Name.ValueString(),
		Address:          address,
		GatewayID:        plan.GatewayID.ValueString(),
		RemoteNetworkID:  plan.RemoteNetworkID.ValueString(),
		IsVisible:        getOptionalBool(plan.IsVisible),
		Alias:            getOptionalString(plan.Alias),
		SecurityPolicyID: plan.SecurityPolicyID.ValueStringPointer(),
		Tags:             getTags(plan.Tags),
		Protocols:        protocols,
		AccessPolicy:     accessPolicy,
		GroupsAccess:     accessGroups,
	})

	r.helper(ctx, k8sRes, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *kubernetesResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state kubernetesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	k8sRes, err := r.client.ReadKubernetesResource(ctx, state.ID.ValueString())

	r.helper(ctx, k8sRes, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

//nolint:funlen
func (r *kubernetesResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan kubernetesResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if !plan.InCluster.ValueBool() {
		if plan.BearerTokenFile.ValueString() == "" {
			addErr(&resp.Diagnostics, ErrBearerTokenFileEmpty, operationUpdate, TwingateKubernetesResource)

			return
		}

		if plan.CAFile.ValueString() == "" {
			addErr(&resp.Diagnostics, ErrCAFileEmpty, operationUpdate, TwingateKubernetesResource)

			return
		}
	}

	var state kubernetesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	accessGroups, err := getGroupAccessAttribute(plan.GroupAccess)
	if err != nil {
		addErr(&resp.Diagnostics, fmt.Errorf("failed to parse access_group: %w", err), operationUpdate, TwingateKubernetesResource)

		return
	}

	prots, err := convertProtocols(&plan.Protocols)
	if err != nil {
		addErr(&resp.Diagnostics, err, operationUpdate, TwingateKubernetesResource)

		return
	}

	accessPolicy, err := getAccessPolicyAttribute(plan.AccessPolicy)
	if err != nil {
		addErr(&resp.Diagnostics, fmt.Errorf("failed to parse access_policy: %w", err), operationUpdate, TwingateKubernetesResource)

		return
	}

	if !plan.GroupAccess.Equal(state.GroupAccess) {
		if err := r.updateK8sResourceAccess(ctx, state.ID.ValueString(), state.GroupAccess, accessGroups); err != nil {
			addErr(&resp.Diagnostics, err, operationUpdate, TwingateKubernetesResource)

			return
		}
	}

	address := plan.Address.ValueString()
	if plan.InCluster.ValueBool() {
		address = defaultKubernetesAddress
	}

	if address == "" {
		addErr(&resp.Diagnostics, ErrAddressEmpty, operationUpdate, TwingateKubernetesResource)

		return
	}

	k8sRes, err := r.client.UpdateKubernetesResource(ctx, &model.KubernetesResource{
		ID:               state.ID.ValueString(),
		Name:             plan.Name.ValueString(),
		Address:          address,
		GatewayID:        plan.GatewayID.ValueString(),
		RemoteNetworkID:  plan.RemoteNetworkID.ValueString(),
		IsVisible:        getOptionalBool(plan.IsVisible),
		Alias:            getOptionalString(plan.Alias),
		SecurityPolicyID: plan.SecurityPolicyID.ValueStringPointer(),
		Tags:             getTags(plan.Tags),
		Protocols:        prots,
		AccessPolicy:     accessPolicy,
		GroupsAccess:     accessGroups,
	})

	r.helper(ctx, k8sRes, &plan, &resp.State, &resp.Diagnostics, err, operationUpdate)
}

func (r *kubernetesResource) updateK8sResourceAccess(ctx context.Context, resourceID string, stateGroupAccess types.Set, planGroups []model.AccessGroup) error {
	oldGroups, err := getGroupAccessAttribute(stateGroupAccess)
	if err != nil {
		return fmt.Errorf("failed to parse access_group: %w", err)
	}

	// setDifferenceGroups returns IDs of groups to remove
	idsToDelete := setDifferenceGroups(oldGroups, planGroups)
	if err := r.client.RemoveResourceAccess(ctx, resourceID, idsToDelete); err != nil {
		return fmt.Errorf("failed to remove resource access: %w", err)
	}

	current, err := r.client.ReadKubernetesResource(ctx, resourceID)
	if err != nil {
		return fmt.Errorf("failed to read resource access: %w", err)
	}

	groupsToAdd := setDifferenceGroupAccess(planGroups, current.GroupsAccess)
	if err := r.client.AddResourceAccess(ctx, resourceID, convertResourceAccess(nil, groupsToAdd)); err != nil {
		return fmt.Errorf("failed to add resource access: %w", err)
	}

	return nil
}

func (r *kubernetesResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state kubernetesResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteKubernetesResource(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateKubernetesResource)
}

//nolint:funlen
func (r *kubernetesResource) helper(ctx context.Context, k8sRes *model.KubernetesResource, state *kubernetesResourceModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateKubernetesResource)

		return
	}

	state.ID = types.StringValue(k8sRes.ID)
	state.Name = types.StringValue(k8sRes.Name)
	state.Address = types.StringValue(k8sRes.Address)
	state.GatewayID = types.StringValue(k8sRes.GatewayID)
	state.RemoteNetworkID = types.StringValue(k8sRes.RemoteNetworkID)
	state.SecurityPolicyID = types.StringPointerValue(k8sRes.SecurityPolicyID)

	if state.BearerTokenFile.IsUnknown() {
		state.BearerTokenFile = types.StringNull()
	}

	if state.CAFile.IsUnknown() {
		state.CAFile = types.StringNull()
	}

	if !state.IsVisible.IsNull() || k8sRes.IsVisible != nil {
		state.IsVisible = types.BoolPointerValue(k8sRes.IsVisible)
	}

	if !state.Alias.IsNull() || k8sRes.Alias != nil {
		state.Alias = types.StringPointerValue(k8sRes.Alias)
	}

	state.Tags = makeMapValue(k8sRes.Tags)

	if k8sRes.Protocols != nil {
		prots, diags := convertProtocolsToTerraform(k8sRes.Protocols, &state.Protocols)
		diagnostics.Append(diags...)

		if diagnostics.HasError() {
			return
		}

		state.Protocols = prots
	}

	referenceAccessPolicy, err := getAccessPolicyAttribute(state.AccessPolicy)
	if err != nil {
		diagnostics.AddAttributeError(
			path.Root(attr.AccessPolicy),
			"failed to parse access_policy attribute",
			err.Error(),
		)

		return
	}

	accessPolicy, diags := convertAccessPolicyToTerraform(ctx, k8sRes.AccessPolicy, referenceAccessPolicy)
	diagnostics.Append(diags...)

	state.AccessPolicy = accessPolicy

	groupAccess, diags := convertGroupsAccessToTerraform(ctx, k8sRes.GroupsAccess, state.GroupAccess)
	diagnostics.Append(diags...)

	state.GroupAccess = groupAccess

	if diagnostics.HasError() {
		return
	}

	diags = respState.Set(ctx, state)
	diagnostics.Append(diags...)
}
