package resource //nolint:dupl

import (
	"context"
	"errors"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customvalidator"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &sshResource{}

func NewSSHResourceResource() resource.Resource {
	return &sshResource{}
}

type sshResource struct {
	client *client.Client
}

type sshResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Address         types.String `tfsdk:"address"`
	GatewayID       types.String `tfsdk:"gateway_id"`
	RemoteNetworkID types.String `tfsdk:"remote_network_id"`
	Username        types.String `tfsdk:"username"`
}

func (r *sshResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateSSHResource
}

func (r *sshResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(*client.Client)
}

func (r *sshResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

func (r *sshResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "SSH Resources are Twingate resources accessed via an SSH Gateway.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the SSH Resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.Name: schema.StringAttribute{
				Required:    true,
				Description: "The name of the SSH Resource.",
			},
			attr.Address: schema.StringAttribute{
				Required:    true,
				Description: "The address of the SSH Resource (IP or FQDN).",
				Validators: []validator.String{
					customvalidator.Address(),
				},
			},
			attr.GatewayID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Gateway used to access this SSH Resource.",
			},
			attr.RemoteNetworkID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Remote Network the SSH Resource belongs to.",
			},
			attr.Username: schema.StringAttribute{
				Optional:    true,
				Description: "The username to use when connecting to the SSH Resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *sshResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan sshResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	sshRes, err := r.client.CreateSSHResource(ctx, &model.SSHResource{
		Name:            plan.Name.ValueString(),
		Address:         plan.Address.ValueString(),
		GatewayID:       plan.GatewayID.ValueString(),
		RemoteNetworkID: plan.RemoteNetworkID.ValueString(),
	})

	r.helper(ctx, sshRes, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *sshResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state sshResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	sshRes, err := r.client.ReadSSHResource(ctx, state.ID.ValueString())

	r.helper(ctx, sshRes, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

func (r *sshResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan sshResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	var state sshResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	sshRes, err := r.client.UpdateSSHResource(ctx, &model.SSHResource{
		ID:              state.ID.ValueString(),
		Name:            plan.Name.ValueString(),
		Address:         plan.Address.ValueString(),
		GatewayID:       plan.GatewayID.ValueString(),
		RemoteNetworkID: plan.RemoteNetworkID.ValueString(),
	})

	r.helper(ctx, sshRes, &plan, &resp.State, &resp.Diagnostics, err, operationUpdate)
}

func (r *sshResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state sshResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteSSHResource(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateSSHResource)
}

func (r *sshResource) helper(ctx context.Context, sshRes *model.SSHResource, state *sshResourceModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateSSHResource)

		return
	}

	state.ID = types.StringValue(sshRes.ID)
	state.Name = types.StringValue(sshRes.Name)
	state.Address = types.StringValue(sshRes.Address)
	state.GatewayID = types.StringValue(sshRes.GatewayID)
	state.RemoteNetworkID = types.StringValue(sshRes.RemoteNetworkID)

	diags := respState.Set(ctx, state)
	diagnostics.Append(diags...)
}
