package resource

import (
	"context"
	"errors"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure the implementation satisfies the desired interfaces.
var _ resource.Resource = &sshCertificateAuthority{}

func NewSSHCertificateAuthorityResource() resource.Resource {
	return &sshCertificateAuthority{}
}

type sshCertificateAuthority struct {
	client *client.Client
}

type sshCertificateAuthorityModel struct {
	ID          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	PublicKey   types.String `tfsdk:"public_key"`
	Fingerprint types.String `tfsdk:"fingerprint"`
}

func (r *sshCertificateAuthority) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateSSHCertificateAuthority
}

func (r *sshCertificateAuthority) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(*client.Client)
}

func (r *sshCertificateAuthority) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

func (r *sshCertificateAuthority) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "SSH Certificate Authorities allow Twingate to sign SSH certificates for authenticating users to resources.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the SSH Certificate Authority.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.Name: schema.StringAttribute{
				Required:    true,
				Description: "The name of the SSH Certificate Authority.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			attr.PublicKey: schema.StringAttribute{
				Required:    true,
				Description: "The SSH public key in OpenSSH authorized_keys format.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			attr.Fingerprint: schema.StringAttribute{
				Computed:    true,
				Description: "The fingerprint of the SSH public key.",
			},
		},
	}
}

func (r *sshCertificateAuthority) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan sshCertificateAuthorityModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ca, err := r.client.CreateSSHCertificateAuthority(ctx, plan.Name.ValueString(), plan.PublicKey.ValueString())

	r.helper(ctx, ca, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *sshCertificateAuthority) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state sshCertificateAuthorityModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ca, err := r.client.ReadSSHCertificateAuthority(ctx, state.ID.ValueString())

	r.helper(ctx, ca, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

func (r *sshCertificateAuthority) Update(_ context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse) {
	// All mutable fields trigger replacement, so Update is never called.
}

func (r *sshCertificateAuthority) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state sshCertificateAuthorityModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteSSHCertificateAuthority(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateSSHCertificateAuthority)
}

func (r *sshCertificateAuthority) helper(ctx context.Context, certificateAuthority *model.CertificateAuthority, state *sshCertificateAuthorityModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateSSHCertificateAuthority)

		return
	}

	state.ID = types.StringValue(certificateAuthority.ID)
	state.Name = types.StringValue(certificateAuthority.Name)
	state.Fingerprint = types.StringValue(certificateAuthority.Fingerprint)
	// PublicKey is not returned by the API; preserve the value already in state.

	diags := respState.Set(ctx, state)
	diagnostics.Append(diags...)
}
