package resource

import (
	"context"
	"errors"
	"fmt"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customplanmodifier"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customvalidator"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/provider/providerdata"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/utils"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	tfattr "github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

var _ resource.Resource = &webAppResource{}

func NewWebAppResourceResource() resource.Resource {
	return &webAppResource{}
}

type webAppResource struct {
	client *client.Client
}

type webAppResourceModel struct {
	ID                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	Address               types.String `tfsdk:"address"`
	GatewayID             types.String `tfsdk:"gateway_id"`
	RemoteNetworkID       types.String `tfsdk:"remote_network_id"`
	IsVisible             types.Bool   `tfsdk:"is_visible"`
	Alias                 types.String `tfsdk:"alias"`
	SecurityPolicyID      types.String `tfsdk:"security_policy_id"`
	Tags                  types.Map    `tfsdk:"tags"`
	Upstream              types.Object `tfsdk:"upstream"`
	Downstream            types.Object `tfsdk:"downstream"`
	RequestHeaderRewrites types.Map    `tfsdk:"request_header_rewrites"`
	AccessPolicy          types.Set    `tfsdk:"access_policy"`
	GroupAccess           types.Set    `tfsdk:"access_group"`
}

type webAppUpstreamModel struct {
	Port types.Int64 `tfsdk:"port"`
	TLS  types.Bool  `tfsdk:"tls"`
}

type webAppDownstreamModel struct {
	Port types.Int64 `tfsdk:"port"`
	TLS  types.Bool  `tfsdk:"tls"`
}

var webAppUpstreamAttributeTypes = map[string]tfattr.Type{ //nolint:gochecknoglobals
	attr.Port: types.Int64Type,
	attr.TLS:  types.BoolType,
}

var webAppDownstreamAttributeTypes = map[string]tfattr.Type{ //nolint:gochecknoglobals
	attr.Port: types.Int64Type,
	attr.TLS:  types.BoolType,
}

func (r *webAppResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateWebAppResource
}

func (r *webAppResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		return
	}

	r.client = providerData.Client
}

func (r *webAppResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

//nolint:funlen
func (r *webAppResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Web App Resources are Twingate resources accessed via a Gateway.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the Web App Resource.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.Name: schema.StringAttribute{
				Required:    true,
				Description: "The name of the Web App Resource.",
			},
			attr.Address: schema.StringAttribute{
				Required:    true,
				Description: "The address of the Web App Resource (IP or FQDN).",
				Validators: []validator.String{
					customvalidator.Address(),
				},
			},
			attr.GatewayID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Gateway used to access this Web App Resource.",
			},
			attr.RemoteNetworkID: schema.StringAttribute{
				Required:    true,
				Description: "The ID of the Remote Network the Web App Resource belongs to.",
			},
			attr.IsVisible: schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Controls whether this Resource will be visible in the main Resource list in the Twingate Client. Default is `true`.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(true),
			},
			attr.Alias: schema.StringAttribute{
				Optional:      true,
				Description:   "Set a DNS alias address for the Resource. Must be a DNS-valid name string.",
				PlanModifiers: []planmodifier.String{customplanmodifier.CaseInsensitiveDiff()},
			},
			attr.SecurityPolicyID: schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "The ID of a `twingate_security_policy` to set as this Resource's Security Policy. Default is 'Null' which points to `Default Policy` on Admin console.",
				PlanModifiers: []planmodifier.String{
					customplanmodifier.UseNullStringWhenValueOmitted(),
				},
			},
			attr.Tags: schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "A map of key-value pair tags to set on this resource.",
				Default:     mapdefault.StaticValue(types.MapNull(types.StringType)),
			},
			attr.Upstream:   webAppUpstream(),
			attr.Downstream: webAppDownstream(),
			attr.RequestHeaderRewrites: schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "A map of HTTP headers to rewrite on requests forwarded to the upstream resource. Header names are compared case-insensitively.",
				Validators: []validator.Map{
					customvalidator.CaseInsensitiveUniqueKeys(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			attr.AccessPolicy: accessPolicyBlock(),
			attr.AccessGroup:  groupAccessBlock(),
		},
	}
}

func webAppUpstream() schema.SingleNestedAttribute {
	return schema.SingleNestedAttribute{
		Required:    true,
		Description: "The upstream configuration. The connection between the Gateway and the upstream resource.",
		Attributes: map[string]schema.Attribute{
			attr.Port: schema.Int64Attribute{
				Required:    true,
				Description: fmt.Sprintf("The port number. Must be between %d and %d inclusive.", model.MinPortValue, model.MaxPortValue),
				Validators: []validator.Int64{
					int64validator.Between(model.MinPortValue, model.MaxPortValue),
				},
			},
			attr.TLS: schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Whether TLS is enabled on the upstream connection. Default is `false`.",
				Default:     booldefault.StaticBool(false),
			},
		},
	}
}

func webAppDownstream() schema.SingleNestedAttribute {
	return schema.SingleNestedAttribute{
		Required:    true,
		Description: "The downstream configuration. The connection between the protocol client and the Gateway.",
		Attributes: map[string]schema.Attribute{
			attr.Port: schema.Int64Attribute{
				Required:    true,
				Description: fmt.Sprintf("The port number. Must be between %d and %d inclusive.", model.MinPortValue, model.MaxPortValue),
				Validators: []validator.Int64{
					int64validator.Between(model.MinPortValue, model.MaxPortValue),
				},
			},
			attr.TLS: schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Whether TLS is enabled on the downstream connection. Default is `false`.",
				Default:     booldefault.StaticBool(false),
			},
		},
	}
}

func webAppUpstreamValue(ctx context.Context, obj types.Object) (webAppUpstreamModel, diag.Diagnostics) {
	var upstream webAppUpstreamModel

	diags := obj.As(ctx, &upstream, basetypes.ObjectAsOptions{})

	return upstream, diags
}

func webAppDownstreamValue(ctx context.Context, obj types.Object) (webAppDownstreamModel, diag.Diagnostics) {
	var downstream webAppDownstreamModel

	diags := obj.As(ctx, &downstream, basetypes.ObjectAsOptions{})

	return downstream, diags
}

func webAppUpstreamObject(ctx context.Context, port int64, tls bool) (types.Object, diag.Diagnostics) {
	return types.ObjectValueFrom(ctx, webAppUpstreamAttributeTypes, webAppUpstreamModel{
		Port: types.Int64Value(port),
		TLS:  types.BoolValue(tls),
	})
}

func webAppDownstreamObject(ctx context.Context, port int64, tls bool) (types.Object, diag.Diagnostics) {
	return types.ObjectValueFrom(ctx, webAppDownstreamAttributeTypes, webAppDownstreamModel{
		Port: types.Int64Value(port),
		TLS:  types.BoolValue(tls),
	})
}

// getHeaderRewrites converts the configured map for the API. Header rewrites and
// tags are both plain string maps, so the tag converter applies: a null, unknown
// or empty map becomes nil, which the client sends as an empty list.
func getHeaderRewrites(rawRewrites types.Map) map[string]string {
	return getTags(rawRewrites)
}

// convertHeaderRewrites maps the API response back into state. The API drops the
// field once it holds no entries, so an empty response is ambiguous: it matches
// both an omitted attribute and an explicitly empty map. Mirror whichever form
// was declared, otherwise `{}` in config would be stored as null and drift on
// every plan.
func convertHeaderRewrites(rewrites map[string]string, state types.Map) types.Map {
	if len(rewrites) > 0 {
		return utils.ConvertMapValue(rewrites)
	}

	if !state.IsNull() && !state.IsUnknown() && len(state.Elements()) == 0 {
		return state
	}

	return types.MapNull(types.StringType)
}

func (r *webAppResource) buildResource(ctx context.Context, plan *webAppResourceModel, diagnostics *diag.Diagnostics, operation string) *model.WebAppResource {
	accessGroups, err := getGroupAccessAttribute(plan.GroupAccess)
	if err != nil {
		addErr(diagnostics, fmt.Errorf("failed to parse access_group: %w", err), operation, TwingateWebAppResource)

		return nil
	}

	accessPolicy, err := getAccessPolicyAttribute(plan.AccessPolicy)
	if err != nil {
		addErr(diagnostics, fmt.Errorf("failed to parse access_policy: %w", err), operation, TwingateWebAppResource)

		return nil
	}

	upstream, diags := webAppUpstreamValue(ctx, plan.Upstream)
	diagnostics.Append(diags...)

	downstream, diags := webAppDownstreamValue(ctx, plan.Downstream)
	diagnostics.Append(diags...)

	if diagnostics.HasError() {
		return nil
	}

	return &model.WebAppResource{
		Name:                  plan.Name.ValueString(),
		Address:               plan.Address.ValueString(),
		GatewayID:             plan.GatewayID.ValueString(),
		RemoteNetworkID:       plan.RemoteNetworkID.ValueString(),
		IsVisible:             getOptionalBool(plan.IsVisible),
		Alias:                 getOptionalString(plan.Alias),
		SecurityPolicyID:      plan.SecurityPolicyID.ValueStringPointer(),
		Tags:                  getTags(plan.Tags),
		Upstream:              model.WebAppUpstream{Port: upstream.Port.ValueInt64(), TLS: upstream.TLS.ValueBool()},
		Downstream:            model.WebAppDownstream{Port: downstream.Port.ValueInt64(), TLS: downstream.TLS.ValueBool()},
		RequestHeaderRewrites: getHeaderRewrites(plan.RequestHeaderRewrites),
		AccessPolicy:          accessPolicy,
		GroupsAccess:          accessGroups,
	}
}

func (r *webAppResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan webAppResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	input := r.buildResource(ctx, &plan, &resp.Diagnostics, operationCreate)
	if resp.Diagnostics.HasError() {
		return
	}

	webAppRes, err := r.client.CreateWebAppResource(ctx, input)

	r.helper(ctx, webAppRes, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *webAppResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state webAppResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	webAppRes, err := r.client.ReadWebAppResource(ctx, state.ID.ValueString())

	r.helper(ctx, webAppRes, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

func (r *webAppResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan webAppResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	var state webAppResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	input := r.buildResource(ctx, &plan, &resp.Diagnostics, operationUpdate)
	if resp.Diagnostics.HasError() {
		return
	}

	if !plan.GroupAccess.Equal(state.GroupAccess) {
		if err := r.updateWebAppResourceAccess(ctx, state.ID.ValueString(), state.GroupAccess, input.GroupsAccess); err != nil {
			addErr(&resp.Diagnostics, err, operationUpdate, TwingateWebAppResource)

			return
		}
	}

	input.ID = state.ID.ValueString()

	webAppRes, err := r.client.UpdateWebAppResource(ctx, input)

	r.helper(ctx, webAppRes, &plan, &resp.State, &resp.Diagnostics, err, operationUpdate)
}

func (r *webAppResource) updateWebAppResourceAccess(ctx context.Context, resourceID string, stateGroupAccess types.Set, planGroups []model.AccessGroup) error {
	oldGroups, err := getGroupAccessAttribute(stateGroupAccess)
	if err != nil {
		return fmt.Errorf("failed to parse access_group: %w", err)
	}

	idsToDelete := setDifferenceGroups(oldGroups, planGroups)
	if err := r.client.RemoveResourceAccess(ctx, resourceID, idsToDelete); err != nil {
		return fmt.Errorf("failed to remove resource access: %w", err)
	}

	current, err := r.client.ReadWebAppResource(ctx, resourceID)
	if err != nil {
		return fmt.Errorf("failed to read resource access: %w", err)
	}

	groupsToAdd := setDifferenceGroupAccess(planGroups, current.GroupsAccess)
	if err := r.client.AddResourceAccess(ctx, resourceID, convertResourceAccess(nil, groupsToAdd)); err != nil {
		return fmt.Errorf("failed to add resource access: %w", err)
	}

	return nil
}

func (r *webAppResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state webAppResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteWebAppResource(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateWebAppResource)
}

//nolint:funlen
func (r *webAppResource) helper(ctx context.Context, webAppRes *model.WebAppResource, state *webAppResourceModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateWebAppResource)

		return
	}

	state.ID = types.StringValue(webAppRes.ID)
	state.Name = types.StringValue(webAppRes.Name)
	state.Address = types.StringValue(webAppRes.Address)
	state.GatewayID = types.StringValue(webAppRes.GatewayID)
	state.RemoteNetworkID = types.StringValue(webAppRes.RemoteNetworkID)
	state.SecurityPolicyID = types.StringPointerValue(webAppRes.SecurityPolicyID)

	if !state.IsVisible.IsNull() || webAppRes.IsVisible != nil {
		state.IsVisible = types.BoolPointerValue(webAppRes.IsVisible)
	}

	if !state.Alias.IsNull() {
		state.Alias = types.StringPointerValue(webAppRes.Alias)
	}

	state.Tags = utils.ConvertMapValue(webAppRes.Tags)
	state.RequestHeaderRewrites = convertHeaderRewrites(webAppRes.RequestHeaderRewrites, state.RequestHeaderRewrites)

	upstream, diags := webAppUpstreamObject(ctx, webAppRes.Upstream.Port, webAppRes.Upstream.TLS)
	diagnostics.Append(diags...)

	downstream, diags := webAppDownstreamObject(ctx, webAppRes.Downstream.Port, webAppRes.Downstream.TLS)
	diagnostics.Append(diags...)

	if diagnostics.HasError() {
		return
	}

	state.Upstream = upstream
	state.Downstream = downstream

	referenceAccessPolicy, err := getAccessPolicyAttribute(state.AccessPolicy)
	if err != nil {
		diagnostics.AddAttributeError(
			path.Root(attr.AccessPolicy),
			"failed to parse access_policy attribute",
			err.Error(),
		)

		return
	}

	accessPolicy, diags := convertAccessPolicyToTerraform(ctx, webAppRes.AccessPolicy, referenceAccessPolicy)
	diagnostics.Append(diags...)

	state.AccessPolicy = accessPolicy

	groupAccess, diags := convertGroupsAccessToTerraform(ctx, webAppRes.GroupsAccess, state.GroupAccess)
	diagnostics.Append(diags...)

	state.GroupAccess = groupAccess

	if diagnostics.HasError() {
		return
	}

	diags = respState.Set(ctx, state)
	diagnostics.Append(diags...)
}
