package resource

import (
	"context"
	"errors"
	"fmt"

	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/attr"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/client"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/customvalidator"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/model"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/provider/providerdata"
	"github.com/Twingate/terraform-provider-twingate/v4/twingate/internal/utils"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure the implementation satisfies the desired interfaces.
var _ resource.Resource = &x509CertificateAuthority{}
var _ resource.ResourceWithModifyPlan = &x509CertificateAuthority{}

func NewX509CertificateAuthorityResource() resource.Resource {
	return &x509CertificateAuthority{}
}

type x509CertificateAuthority struct {
	client *client.Client
}

type x509CertificateAuthorityModel struct {
	ID          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Certificate types.String `tfsdk:"certificate"`
	Fingerprint types.String `tfsdk:"fingerprint"`
}

func (r *x509CertificateAuthority) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TwingateX509CertificateAuthority
}

func (r *x509CertificateAuthority) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		return
	}

	r.client = providerData.Client
}

func (r *x509CertificateAuthority) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root(attr.ID), req, resp)
}

func (r *x509CertificateAuthority) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "X509 Certificate Authorities allow Twingate to verify certificates presented by resources during TLS connections.",
		Attributes: map[string]schema.Attribute{
			attr.ID: schema.StringAttribute{
				Computed:    true,
				Description: "Autogenerated ID of the X509 Certificate Authority.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			attr.Name: schema.StringAttribute{
				Required:    true,
				Description: "The name of the X509 Certificate Authority.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			attr.Certificate: schema.StringAttribute{
				Required:    true,
				WriteOnly:   true,
				Description: "The PEM-encoded X509 certificate. This field is write-only and will not be returned by the API.",
				Validators: []validator.String{
					customvalidator.Certificate(),
				},
			},
			attr.Fingerprint: schema.StringAttribute{
				Computed:    true,
				Description: "The SHA-256 fingerprint of the X509 certificate.",
			},
		},
	}
}

func (r *x509CertificateAuthority) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan x509CertificateAuthorityModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// WriteOnly attributes are not populated in the plan; read them from config.
	var config x509CertificateAuthorityModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ca, err := r.client.CreateX509CertificateAuthority(ctx, plan.Name.ValueString(), config.Certificate.ValueString())

	r.helper(ctx, ca, &plan, &resp.State, &resp.Diagnostics, err, operationCreate)
}

func (r *x509CertificateAuthority) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state x509CertificateAuthorityModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ca, err := r.client.ReadX509CertificateAuthority(ctx, state.ID.ValueString())

	r.helper(ctx, ca, &state, &resp.State, &resp.Diagnostics, err, operationRead)
}

func (r *x509CertificateAuthority) Update(_ context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse) {
	// All mutable fields trigger replacement, so Update is never called.
}

func (r *x509CertificateAuthority) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state x509CertificateAuthorityModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteX509CertificateAuthority(ctx, state.ID.ValueString())
	addErr(&resp.Diagnostics, err, operationDelete, TwingateX509CertificateAuthority)
}

func (r *x509CertificateAuthority) helper(ctx context.Context, certificateAuthority *model.CertificateAuthority, state *x509CertificateAuthorityModel, respState *tfsdk.State, diagnostics *diag.Diagnostics, err error, operation string) {
	if err != nil {
		if errors.Is(err, client.ErrGraphqlResultIsEmpty) {
			respState.RemoveResource(ctx)

			return
		}

		addErr(diagnostics, err, operation, TwingateX509CertificateAuthority)

		return
	}

	state.ID = types.StringValue(certificateAuthority.ID)
	state.Name = types.StringValue(certificateAuthority.Name)
	// instead of a certificate - we store its fingerprint
	state.Fingerprint = types.StringValue(certificateAuthority.Fingerprint)

	diags := respState.Set(ctx, state)
	diagnostics.Append(diags...)
}

// ModifyPlan triggers resource replacement when the certificate content changes.
// It reads the certificate from config (write-only values are unavailable in the plan),
// computes its fingerprint, and compares it with the fingerprint stored in state.
func (r *x509CertificateAuthority) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// Skip on create (state is null) or delete (plan is null).
	if req.State.Raw.IsNull() || req.Plan.Raw.IsNull() {
		return
	}

	var stateFingerprint types.String

	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root(attr.Fingerprint), &stateFingerprint)...)

	if resp.Diagnostics.HasError() || stateFingerprint.IsNull() || stateFingerprint.IsUnknown() {
		return
	}

	var certValue types.String

	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root(attr.Certificate), &certValue)...)

	if resp.Diagnostics.HasError() || certValue.IsNull() || certValue.IsUnknown() {
		return
	}

	newFingerprint, err := utils.CalculateCertificateFingerprint(certValue.ValueString())
	if err != nil {
		resp.Diagnostics.AddAttributeError(
			path.Root(attr.Certificate),
			"Invalid certificate",
			fmt.Sprintf("Could not calculate fingerprint: %s", err),
		)

		return
	}

	if stateFingerprint.ValueString() != newFingerprint {
		resp.RequiresReplace = append(resp.RequiresReplace, path.Root(attr.Certificate))
	}
}
