name: "PR Checks"
permissions: read-all
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

# Ensures only 1 action runs per PR and previous is canceled on new trigger
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-pr:
    name: "Verify PR title and desc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/danger-js@9.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
